### ISSUE TITLE
"1.4.6 Dart和Java及JavaScript对比"里关于CoffeeScript和Flow的描述有误

### ISSUE THREAD

**Issue by BlackGlory** [flutterchina/flutter_in_action_2nd#10]
1. CoffeeScript不应该与TypeScript和Flow一同出现, 因为CoffeeScript和类型没有任何关系, 它唯一支持类型的方式是通过注释添加Flow的Type Annotations.
2. "Flow是否是JavaScript的超集"相关的注释在此无关紧要, 因为"超集"这个说法只是TypeScript的技术营销, 没有实际意义.

**Comment by wendux** [comment]
这块已经修改过了
