### ISSUE TITLE
2.4.1 中 textButton 组件无textColor 属性，flutter 版本 2.10.3

### ISSUE THREAD

**Issue by He2008** [flutterchina/flutter_in_action_2nd#103]
<img width="855" alt="image" src="https://user-images.githubusercontent.com/19567128/158928571-c4301679-9abe-4678-b7b6-1e2fdb254c49.png">
<img width="406" alt="image" src="https://user-images.githubusercontent.com/19567128/158928641-18a086d0-1751-458b-9b0d-bf6643749823.png">

**Comment by wendux** [comment]
fixed
