### ISSUE TITLE
勘误-1.2.2、1.3.3、2.2.1

### ISSUE THREAD

**Issue by wdeo3601** [flutterchina/flutter_in_action_2nd#141]
1.2.2 中，其中 `1.框架层` 中的 Rendering 层介绍中，"Rendering 层，即渲染层，这一层是一个抽象的布局层，它依赖于 Dart UI 层，渲染层会构建一棵由`可渲染对象的组成的`渲染树"，应该为`可渲染对象组成的`   
1.3.3 中，`1. 连接连接Android模拟器` 下的第三点，"为要模拟的Android版本选择一个或多个`系统印象`"，应为`系统镜像`    
2.2.1 中，最后一段“Flutter 中是通过 Widget 嵌套 Widget 的方式来构建UI和进行`实践`处理的，所以记住，Flutter 中万物皆为Widget。”，应该为`事件`

**Comment by wendux** [comment]
updated
