### ISSUE TITLE
uni-app算哪一种,佬

### ISSUE THREAD

**Issue by lydlovezjr** [flutterchina/flutter_in_action_2nd#152]
根据其原理，主要分为三类：

H5 + 原生（Cordova、Ionic、微信小程序）
JavaScript 开发 + 原生渲染 （React Native、Weex）
自绘UI + 原生 (Qt for mobile、Flutter)

**Comment by darkengine** [comment]
“UniApp 跨平台的原理是通过将前端代码打包成Web 页面，然后通过各个平台的Webview 技术在各个平台上显示”

所以uni-app最接近第一种
