### ISSUE TITLE
错别字，多字

### ISSUE THREAD

**Issue by TuringZhu** [flutterchina/flutter_in_action_2nd#154]
https://github.com/flutterchina/flutter_in_action_2nd/blob/main/src/chapter1/flutter_intro.md?plain=1#L37

这里应为:

---

**基于 JIT 的快速开发周期**：Flutter 在开发阶段采用 JIT 模式，这样就避免了每次改动都要进行编译，极大的节省了开发时间

---

多了个`采用，`

**Comment by user-leaf** [comment]
https://github.com/flutterchina/flutter_in_action_2nd/blob/3e7beecc306a835817f6de7d4aaba034772f8c74/src/chapter1/flutter_intro.md?plain=1#L29
“实施” 应为 “实时”

**Comment by wendux** [comment]
updated
