### ISSUE TITLE
https://book.flutterchina.club/chapter3/buttons.html#_3-2-4-iconbutton   OutlineButton=>OutlinedButton

### ISSUE THREAD

**Issue by meicy** [flutterchina/flutter_in_action_2nd#166]
最新的版本有修改
OutlineButton 更改为OutlinedButton 
OutlineButton.icon 同理 改为 OutlinedButton.icon

**Comment by HanHan666666** [comment]
折腾了一早上，在这里找到原因了。。。。。。
![image](https://user-images.githubusercontent.com/60591430/211227847-34ec805b-1124-49fb-bb62-ca1b69342a27.png)

**Comment by wendux** [comment]
updated
