### ISSUE TITLE
https://book.flutterchina.club/chapter7/inherited_widget.html#_7-2-1-inheritedwidget  

### ISSUE THREAD

**Issue by meicy** [flutterchina/flutter_in_action_2nd#169]
版本flutter 3 报错
context.getElementForInheritedWidgetOfExactType<ShareDataWidget>().widget;  => context.getElementForInheritedWidgetOfExactType<ShareDataWidget>()!.widget as ShareDataWidget;

**Comment by wendux** [comment]
updated
