### ISSUE TITLE
第十章 10.8文章内代码示例错误

### ISSUE THREAD

**Issue by MiracleWhite** [flutterchina/flutter_in_action_2nd#184]
文章内10.8离屏绘制部分代码示例
<img width="760" alt="image" src="https://user-images.githubusercontent.com/15857533/228422939-5dad4cef-ab2c-4a71-8754-458243fae2c9.png">
这里会报错，参数缺少屏幕大小
组件库中代码是：
<img width="576" alt="image" src="https://user-images.githubusercontent.com/15857533/228423035-f7689fd8-2775-4ae2-9558-f4451022be00.png">
建议修改

**Comment by wendux** [comment]
done
