### ISSUE TITLE
勘误：多了字

### ISSUE THREAD

**Issue by ilgnefz** [flutterchina/flutter_in_action_2nd#19]
在 6.3 章节介绍 ListView 的 prototypeItem 时结尾多了“如果”两个字

**Comment by wendux** [comment]
没找到....

**Comment by ilgnefz** [comment]
> 没找到....

![QQ截图20211008085128](https://user-images.githubusercontent.com/58471330/136481505-1e5501e9-ecc6-4b77-af9e-ef4db0db171e.png)

**Comment by wendux** [comment]
get
