### ISSUE TITLE
勘误：一个加粗标记的错误

### ISSUE THREAD

**Issue by xiaoke0O** [flutterchina/flutter_in_action_2nd#21]
偏后部分的 `而术语 **DOM操作 **就是指` 应改为 `而术语 **DOM操作**就是指`

https://github.com/flutterchina/flutter_in_action_2nd/blob/2c0a4aee91783d2ad13460e9396c0fd6829048c8/src/chapter1/mobile_development_intro.md#L116

![加粗标记没有起作用](https://user-images.githubusercontent.com/46664191/136542117-4765a8b3-cbc8-4204-b79b-60b15fb29e7c.png)

**Comment by wendux** [comment]
get
