### ISSUE TITLE
勘误：从新 => 重新

### ISSUE THREAD

**Issue by dreamer2q** [flutterchina/flutter_in_action_2nd#23]
![image](https://user-images.githubusercontent.com/56211747/136728583-84d2a8f8-ec17-4310-9bac-8db710bc2eb5.png)

https://book.flutterchina.club/chapter14/flutter_app_startup.html#_14-3-2-%E6%B8%B2%E6%9F%93%E7%AE%A1%E7%BA%BF

**Comment by dreamer2q** [comment]
![Screenshot_20211011_150651](https://user-images.githubusercontent.com/56211747/136766088-62187084-8c93-4904-99c3-877f282250bb.jpg)

**Comment by dreamer2q** [comment]
![Screenshot_20211011_153216](https://user-images.githubusercontent.com/56211747/136766125-99cf200f-09d6-4104-b6f2-c93e29290c95.jpg)

**Comment by dreamer2q** [comment]
![image](https://user-images.githubusercontent.com/56211747/136785021-e6bf7ca1-cafd-4005-9014-144ebcc8150a.png)

多余“啊”

**Comment by wendux** [comment]
get
