### ISSUE TITLE
勘误：重复字

### ISSUE THREAD

**Issue by dreamer2q** [flutterchina/flutter_in_action_2nd#25]
![image](https://user-images.githubusercontent.com/56211747/136729108-9c052a82-4fef-42c8-98a8-d74a9f4629b9.png)

https://book.flutterchina.club/chapter14/flutter_app_startup.html#_14-3-2-%E6%B8%B2%E6%9F%93%E7%AE%A1%E7%BA%BF

**Comment by wendux** [comment]
get
