### ISSUE TITLE
Dart 语言简介 函数部分有误

### ISSUE THREAD

**Issue by YM-BH** [flutterchina/flutter_in_action_2nd#30]
定义函数时，可选的位置参数和命名可选参数，需要再类型前加 ?。或者给参数设置默认值
例子：
void say(name, {int age = 0, double? height = 0.0}) {
  print("name is $name, age is $age and height is $height");
}
void sayHello(name, [int? age = 0, double height = 0.0]) {
  print("name is $name, age is $age and height is $height");
}

**Comment by wendux** [comment]
已修改
