### ISSUE TITLE
animatedList code bug

### ISSUE THREAD

**Issue by FycGitHub** [flutterchina/flutter_in_action_2nd#33]
var item = buildItem(context, index);
 data.removeAt(index);
 print('删除 ${data[index]}');

Should be changed to
 var item = buildItem(context, index);
 print('删除 ${data[index]}');
 data.removeAt(index);

**Comment by hevi1991** [comment]
此实例，若点击删除过快，会发生数组越界的异常

**Comment by wendux** [comment]
get
