### ISSUE TITLE
2.5.0版本很多更新后有改变 很多编译不过去

### ISSUE THREAD

**Issue by xiaoxiaoxiaoguaishou** [flutterchina/flutter_in_action_2nd#42]
3.5  FocusScopeNode focusScopeNode;必须初始化 然后RaisdButton在2.5.0版本就被废弃了 。
然后需要一个父组件
`The following assertion was thrown building TextField(focusNode: FocusNode#5550e, decoration: InputDecoration(labelText: "input2"), dirty, dependencies: [MediaQuery, UnmanagedRestorationScope], state: _TextFieldState#72f17):
No Material widget found.`
为控制焦点部分
更新2.5.0版本后很多错误了 希望改正

**Comment by wendux** [comment]
get
