### ISSUE TITLE
3.2 按钮， 部分组件文字未更新

### ISSUE THREAD

**Issue by add358** [flutterchina/flutter_in_action_2nd#5]
原文：Material 组件库中提供了多种按钮组件如ElevatedButton、FlatButton、OutlineButton等，它们都是直接或间接对RawMaterialButton组件的包装定制，所以他们大多数属性都和RawMaterialButton一样。

其中的`FlatButton` 应该改成 `TextButton`, 然后三个Button是继承`ButtonStyleButton`.

**Comment by wendux** [comment]
已更新，thanks。
