### ISSUE TITLE
为什么要将-build-方法放在-state-中-而不是放在statefulwidget中

### ISSUE THREAD

**Issue by gaojunming** [flutterchina/flutter_in_action_2nd#52]
https://book.flutterchina.club/chapter2/first_flutter_app.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E8%A6%81%E5%B0%86-build-%E6%96%B9%E6%B3%95%E6%94%BE%E5%9C%A8-state-%E4%B8%AD-%E8%80%8C%E4%B8%8D%E6%98%AF%E6%94%BE%E5%9C%A8statefulwidget%E4%B8%AD

看完作者的解释还是不能明白，为什么不把state和build都放在widget中？更新状态仍然可以使用setState方法。为了维护状态专门新建一个state类有必要吗？

**Comment by itwenhao123456** [comment]
他这个写得确实是不那么通俗易懂，我来给你解释下，一句话说清楚：
最显而易见的一个解释就是，你要知道Widget是经常需要更新重新生成的，但是他对应State却不是（他只是在Element第一次或者重新生成才会生成）所以这里分开是非常有必要的，如果你搞清楚了Widget，State，Element，RenderObject调用的流程的时候你就很清楚这个到底是为什么了···

**Comment by gaojunming** [comment]
> 他这个写得确实是不那么通俗易懂，我来给你解释下，一句话说清楚： 最显而易见的一个解释就是，你要知道Widget是经常需要更新重新生成的，但是他对应State却不是（他只是在Element第一次或者重新生成才会生成）所以这里分开是非常有必要的，如果你搞清楚了Widget，State，Element，RenderObject调用的流程的时候你就很清楚这个到底是为什么了···

了解了，谢谢
