### ISSUE TITLE
10.8水印实例：文本绘制与离屏渲染代码缺失

### ISSUE THREAD

**Issue by aNaN9811** [flutterchina/flutter_in_action_2nd#53]
10.8.3文本水印画笔：

1、TextWaterMarkPainter 缺少 textDirection 属性对象

2、绘制文本 _textStyle 缺少 _handleTextStyle 方法

章末缺少完整实例，文章代码有点混乱

**Comment by wendux** [comment]
完整代码见flukit组件库中：https://github.com/flutterchina/flukit/blob/main/package_src/lib/src/watermark.dart
