### ISSUE TITLE
第二章 2.2 Widget 简介 didChangeDependencies什么时候调用介绍不足

### ISSUE THREAD

**Issue by itwenhao123456** [flutterchina/flutter_in_action_2nd#57]
**你好，你的文章我觉得写得很好，但是我看到了一些描述，或者文字有出入的地方，还是希望给你指出来：
比如 第二章 2.2 Widget 简介 didChangeDependencies什么时候调，这里只介绍了如下：**

didChangeDependencies()：当State对象的依赖发生变化时会被调用；例如：在之前build() 中包含了一个InheritedWidget，然后在之后的build() 中Inherited widget发生了变化，那么此时Inherited widget的子 widget 的didChangeDependencies()回调都会被调用

**但是对象的didChangeDependencies很常见的是在于对象第一次被创建和挂载的时候（包括重创建）对应的didChangeDependencies也会调用，希望在书里面加上这个最常见的调用形式**

**我的一偏博客也写到了这个话题 https://www.jianshu.com/p/287e3c6210fb** 
**我的邮箱如下 itwenhao123@126.com 希望能有交流···**

**Comment by wendux** [comment]
已添加
