### ISSUE TITLE
第七章 7.2 数据共享 介绍updateShouldNotify的作用描述不足

### ISSUE THREAD

**Issue by itwenhao123456** [flutterchina/flutter_in_action_2nd#58]
**你好，你的文章我觉得写得很好，但是我看到了一些描述，或者文字有出入的地方，还是希望给你指出来：
比如 第七章 7.2 数据共享 简介 updateShouldNotify的作用的时候如下：**

//该回调决定当data发生变化时，是否通知子树中依赖data的Widget
  @override
  bool updateShouldNotify(ShareDataWidget old) {
    return old.data != data;
  }

**其实updateShouldNotify这个方法最重要的一面确实是决定是否通知子树中依赖data的Widget，但是他这个函数还有一个隐含的作用就是决定依赖的子Widget是否能够调用build方法重建，究其原因在于他的build方法只是返回了child并没有像普通对象一样调用state.build方法，希望书里面还是帮助补充一下这个很容易被忽略比较隐含的寓意**

**我的这偏博客末尾也写到了这个话题 https://www.jianshu.com/p/287e3c6210fb** 
**我的邮箱如下 itwenhao123@126.com 希望能有交流···**

**Comment by wendux** [comment]
已优化
