### ISSUE TITLE
第四章 4.8.2 AfterLayout

### ISSUE THREAD

**Issue by itwenhao123456** [flutterchina/flutter_in_action_2nd#59]
**你好，你的文章我觉得写得很好，但是我看到了一些描述，或者文字有出入的地方，还是希望给你指出来：
第四章 4.8.2 AfterLayout 简介 AfterLayout**

**我的环境如下：
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (6 months ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4**

**在我的环境下面已经看不到AfterLayout这个组件了，这个组件如果已经被移除了的话在书里面应该要加上说明为好**

我的邮箱如下 itwenhao123@126.com 希望能有交流···

**Comment by wendux** [comment]
![image](https://user-images.githubusercontent.com/20411648/148671999-60767a8d-e7d3-4371-9b66-156549ae8b14.png)
