### ISSUE TITLE
第八章 8.3 Flutter事件机制

### ISSUE THREAD

**Issue by itwenhao123456** [flutterchina/flutter_in_action_2nd#60]
**你好，你的文章我觉得写得很好，但是我看到了一些描述，或者文字有出入的地方，还是希望给你指出来：
第八章 8.3 Flutter事件机制有一段代码和描述如下：**

  Widget wChild(int index) {
    return Listener(
      onPointerDown: (e) => print(index),
      child: Container(
        width: 100,
        height: 100,
        color: Colors.grey,
      ),
    );
  }

答案是只会打印一个 '2'，原因是，Stack 先遍历第二个子节点 Listener ，因为 Container 的 hitTest 会返回 true（实际是 Container 内部的 DecoratedBox ）**（这句话有问题）**，所以 Listener 的 hitTestChildren 会返回 true，最终 Listener 的hitTest 也会返回true，所以第一个子节点将不会收到事件。

**其实这里描述有问题，这个Demo里面Container只有width，height，color属性，所以他在这里面应该是一个ColoredBox对应的renderObject是_RenderColoredBox，这里的描述是有问题的，你校对过以后还是改正为好**

**我的邮箱如下 itwenhao123@126.com 希望能有交流···**

**Comment by wendux** [comment]
已修改
