### ISSUE TITLE
7.3 跨组件状态共享（Provider）示例代码报provider为空的错误

### ISSUE THREAD

**Issue by dany2fiona** [flutterchina/flutter_in_action_2nd#61]
![image](https://user-images.githubusercontent.com/20991725/147220009-59ea0fa7-51af-4003-a7ff-a630d038d61a.png)
麻烦帮看看哪里出问题了

**Comment by itwenhao123456** [comment]
应该是可以运行的吧，你看看那个of方法你是怎么写的？···

**Comment by dany2fiona** [comment]
可以运行了，createState没有加泛型导致默认变成StatelessElement了

**Comment by dany2fiona** [comment]
![image](https://user-images.githubusercontent.com/20991725/147517287-73d3f11b-4d5d-49ce-b4f4-1bbbe1feca05.png)
