### ISSUE TITLE
第八章 8.3.5 HitTestBehavior

### ISSUE THREAD

**Issue by itwenhao123456** [flutterchina/flutter_in_action_2nd#63]
**你好，你的文章我觉得写得很好，但是我看到了一些描述，或者文字有出入的地方，还是希望给你指出来：
第八章 8.3.5 HitTestBehavior事件机制有一段代码和描述如下：**

behavior 为 deferToChild 时，hitTestSelf 返回 false，当前组件是否能通过命中测试完全取决于 hitTestChildren 的返回值。也就是说只要有一个子节点通过命中测试，则当前组件便会通过命中测试。
behavior 为 opaque 时，hitTestSelf 返回 true，hitTarget 值始终为 true，当前组件通过命中测试。
behavior 为 translucent 时，hitTestSelf 返回 false，hitTarget 值此时取决于 hitTestChildren 的返回值，但是无论 hitTarget 值是什么，当前节点都会被添加到 HitTestResult 中。

**你这里解释了HitTestBehavior对应三个值的意思，但是你这个解释只是把代码运行直接翻译成了语言，并没有通俗易懂的解释了这个问题，如果是一个初学者估计看了等于没有看，特别是在解释opaque还漏了背后的含义就是”他阻碍了他的前兄弟节点不能被命中“**

**我这里有一个通俗的解说方法，可以给你借鉴下：**

deferToChild： 命中测试决定于子组件是否通过命中测试
opaque：顾名思义不透明的，也就是说自己接收命中测试，但是会阻碍前兄弟节点进行命中测试
translucent：顾名思义半透明，也就是说自己可以命中测试，但是不会阻碍前兄弟节点进行命中测试

**你可以参考下，加上这些通俗易懂的文字这样描述的话，那么大家看起来就心领神会了**

**我的这篇博客也写到了这个话题 https://www.jianshu.com/p/8d0cac1699fa
我的邮箱如下 itwenhao123@126.com 希望能有交流···**

**Comment by wendux** [comment]
这里的行文思路是结合源码一步步分析探索的，并不是急于给出结论
