### ISSUE TITLE
第二章 2.8.1 Dart单线程模型

### ISSUE THREAD

**Issue by itwenhao123456** [flutterchina/flutter_in_action_2nd#65]
**你好，你的文章我觉得写得很好，但是我看到了一些描述，或者文字有出入的地方，还是希望给你指出来：
第二章 2.8.1 Dart单线程模型开头说到如下：**

”在 Java 和 Objective-C（以下简称“OC”）中，如果程序发生异常且没有被捕获，那么程序将会终止“

**其实这句话是有明显问题的，做过iOS都知道OC里面的有些异常是try/catch捕获不到的，比如野指针异常，所以OC里面tr/catch用得很少，而做过Android都知道JAVA里面try/catch确实是可以捕获你所有想要的异常的，而我两个平台都做过，所以我明白你这句话的描述是有问题的，希望纠正这个错误的描述，谢谢**

我的邮箱如下 itwenhao123@126.com 希望能有交流···

**Comment by wendux** [comment]
这里说的异常捕获并不仅限于try catch，而是指没有意料到且没有进行容错处理的情况
