### ISSUE TITLE
第十章 10.4 CustomPaint 与 Canvas

### ISSUE THREAD

**Issue by itwenhao123456** [flutterchina/flutter_in_action_2nd#66]
**你好，你的文章我觉得写得很好，但是我看到了一些描述，或者文字有出入的地方，还是希望给你指出来：
第十章 10.4 CustomPaint 与 Canvas 在防止意外重绘说到如下：**

”我们在上例的基础上添加一个 ElevatedButton，点击后什么也不做：
运行后我们点击“刷新”按钮：“

`class CustomPaintRoute extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          RepaintBoundary(
            child: CustomPaint(
              size: Size(300, 300), //指定画布大小
              painter: MyPainter(),
            ),
          ),
          //添加一个刷新button
          ElevatedButton(onPressed: () {}, child: Text("刷新"))
        ],
      ),
    );
  }
}`

“发现日志面板输出了很多 “paint”，也就是说在点击按钮的时候发生了多次重绘”

**其实这这个例子里面你已经加上了RepaintBoundary边界了，所以没有重绘了，也就不会有很多 “paint”输出了，这里应该是先去掉RepaintBoundary想说明重绘的例子，这里应该是一个版书出错的问题，应要改一下，免得大家误解**

**我的邮箱如下 itwenhao123@126.com 希望能有交流···**

**Comment by wendux** [comment]
fixed
