### ISSUE TITLE
第二版中关于国际化

### ISSUE THREAD

**Issue by zmtzawqlp** [flutterchina/flutter_in_action_2nd#67]
第二版中关于国际化，现在已经可以自动生成代码了。希望作者有空更新下内容，毕竟我们都是看您的文档入门的。

https://flutter.cn/docs/development/accessibility-and-localization/internationalization

**Comment by flycumt** [comment]
soga，原来现在可以自动生成了吗！我还在纠结2.8.1SDK中使用最新的 intl: ^0.17.0和intl_translation: ^0.17.10+1这两个版本依赖冲突的问题，怎么都搞不定，结果好不容易找了个intl_utils代替的才好，早知道官方有方案就不折腾了。。。

**Comment by wendux** [comment]
官方有自动生成的方案，但在文件改动后经常会出现生成不及时导致ide标红的问题；这部分内容第二版中已经更新，可以查看

**Comment by zmtzawqlp** [comment]
> 官方有自动生成的方案，但在文件改动后经常会出现生成不及时导致ide标红的问题；这部分内容第二版中已经更新，可以查看

确实是这样的。所以我现在用的 flutter gen-l10n 命令+  synthetic-package: false 这样会生成文件到项目里面，而不是.dart_tools里面。不知道官方啥时候能修复下
