### ISSUE TITLE
 勘误：5.1 填充（Padding）和5.7.2 实例：单行缩放布局

### ISSUE THREAD

**Issue by hxh696** [flutterchina/flutter_in_action_2nd#68]
5.1填充（Padding）

示例代码中
Padding(
            // 分别指定四个方向的补白
            **_padding: const EdgeInsets.fromLTRB(20.0, 20.0, 20.0, 20.0),_**
            child: Text("Your friend"),
错误：padding: const EdgeInsets.fromLTRB(20.0,.0,20.0,20.0)，
正确：padding: const EdgeInsets.fromLTRB(20.0,20.0,20.0,20.0)，

5.7.2实例：单行布局

第一段代码示例
wRow(' 90000000000000000 '),
          FittedBox(child: wRow(' 90000000000000000 ')),
          wRow(' 800 '),
          **_FittedBox(child: wRow1(' 800 ')),_**
    		]
        .map((e) => Padding(
              padding: EdgeInsets.symmetric(vertical: 20),
              child: e,
            ))
        .toList();,
错误：FittedBox(child: wRow1(' 800 '))，
正确：FittedBox(child: wRow(' 800 '))，

**Comment by wendux** [comment]
fixed
