### ISSUE TITLE
第十四章 14.7 绘制（三）Layer 实例 描述不够准确

### ISSUE THREAD

**Issue by itwenhao123456** [flutterchina/flutter_in_action_2nd#71]
**你好，你的文章我觉得写得很好，但是我看到了一些描述，或者文字有出入的地方，还是希望给你指出来：
第十四章 14.7 绘制（三）Layer 实例里面描述如下：**

在实际开发中，要实现上述功能还是优先使用Flutter建议的”Widget组合“的方式：比如棋盘和棋子分别绘制在两个Widget中，然后把他们添加到一个Stack中，这样做到分层渲染。不过，本节主要是为了说明Flutter自定义组件中如何使用Layer，所以我们采用自定义RenderObject的方式来实现。

其实这里如果棋盘与棋子只是在Stack中作为两个普通的child的话那么应该是不能完全解决分层渲染的问题吧，如果这两个child不是边界渲染RepaintBoundary的话那么棋子的paint还是会触发棋盘的paint的，我觉得这里应该把描述限定得更好一些···

**我的邮箱如下 itwenhao123@126.com 希望能有交流···**

**Comment by wendux** [comment]
这里主要是想说可以“分开”绘制，是不够准确，修改一下
