### ISSUE TITLE
overflow 已经 deprecated

### ISSUE THREAD

**Issue by duhongwei** [flutterchina/flutter_in_action_2nd#72]
4.6 层叠布局 Stack、Positioned 中的  overflow

@Deprecated('Use clipBehavior instead. See the migration guide in flutter.dev/go/clip-behavior. ' 'This feature was deprecated after v1.22.0-12.0.pre.'), final     

https://api.flutter.dev/flutter/widgets/Stack-class.html

**Comment by wendux** [comment]
已修改
