### ISSUE TITLE
14.4.4 flushLayout()介绍中“新的 frame 到来时就会执行 piplineOwner.drawFrame 方法”描述有误

### ISSUE THREAD

**Issue by flycumt** [flutterchina/flutter_in_action_2nd#79]
我是基于2.8的源码看的，**首先，PipelineOwner类当中并没有 drawFrame()  方法。。**
1. 当组件布局发生变化，会调用当前widget对应的RenderObject的 markNeedsLayout() 方法，将此对象的布局信息标记为dirty。具体的在markNeedsLayout() 方法中，判断当前对象是否是relayoutBoundary 布局边界，如果不是，调用markParentNeedsLayout()方法交由父组件递归查找 ，如果是，就将当前对象加入到当前对象的 piplineOwner的需要更新的布局边界节点列表_nodesNeedingLayout中，然后调用piplineOwner的requestVisualUpdate()方法（**markNeedsLayout()代码块中你的注释写的有点问题，你可以仔细检查看一下**）
2. 我观察 PipelineOwner 类，并没有 drawFrame()  方法，然后我观察requestVisualUpdate()方法是在它的构造函数中传入，而PipelineOwner 构造是在RendererBinding混入类的initInstances()方法中调用的，在这个方法里将requestVisualUpdate赋值为ensureVisualUpdate方法，同时会调用addPersistentFrameCallback(_handlePersistentFrameCallback)添加了一个callback，在这个callback中会调用drawFrame()方法。而在ensureVisualUpdate方法中判断了schedulerPhase枚举如果是 idle 或 postFrameCallbacks 阶段才会调用scheduleFrame()去请求新的 frame，新的frame到来时，SchedulerBinding会依次调用 handleBeginFrame --> handleDrawFrame，在handleDrawFrame方法中会调用addPersistentFrameCallback和addPostFrameCallback添加的回调， 因此就会调用到在前面RendererBinding的initInstances()方法中添加的_handlePersistentFrameCallback里面的drawFrame()方法。（**这里还有一个点就是前面你文中14.3.2提到在handleDrawFrame方法中会依次调用4个队列，但是我找了下发现只有3个，还有一个transientCallbacks是在handleBeginFrame 方法中调用的**）
3. **drawFrame()方法是在RendererBinding类定义的**，而WidgetsBinding继承了这个类，因此实际上是调用了WidgetsBinding的drawFrame()方法，在这个方法中又调用了它父类RendererBinding持有的piplineOwner的flushLayout()、flushCompositingBits()、flushPaint()等方法，**所以。。我认为文中描述的“新的 frame 到来时就会执行 piplineOwner.drawFrame 方法”欠妥！** 写技术类的书，不能马马虎虎，要说清楚讲明白，因为有人会参考你的书，你写错了，别人就会按照错误的方向去理解。。
4. 个人建议多画点流程图和时序图吧，大段大段的文字看得不是很舒服

**Comment by itwenhao123456** [comment]
你说的我看了下大体上都没有问题，有可能他原来写的代码比较老了，作者的水平没有问题，但是他这里写得其实并不是很流畅没有把细节都串起来，关于这个章节的问题我也提醒过作者了估计他还没来得及更新，我这里有一篇前段时间整理的博客也写到了这些内容，欢迎讨论
https://www.jianshu.com/p/b34e46462594
···

**Comment by wendux** [comment]
1. drawFrame 确实是在RendererBinding中的，这个是笔误。
2. markNeedsLayout 注释已经修改。
3. “依次调用4个队列” 是新的frame到来后要做的事情，调用的地方是在handleBeginFrame 和 handleDrawFrame中。代码组织上这两个函数完全可以合成一个；这块的重点是要知道调用那四个队列，不同队列任务的区别是什么。

其实，这部分主要是对布局主流程的补充，并不想讨论细节，讨论哪个函数调用哪个函数意义不大（调用栈太深了，并且不同版本的源码可能会改动），所以这两节的主要行文思路是说清主流程：布局变化时，对需要重新布局的节点要进行标记（至于标记的范围属于细节），标记完后在新的frame中对这些节点重新布局。

**Comment by fzyzcjy** [comment]
？？？@错人了...?
