### ISSUE TITLE
@mustCallSuper 标记的方法调用并不都是先调用父类

### ISSUE THREAD

**Issue by xioFei** [flutterchina/flutter_in_action_2nd#84]
![image](https://user-images.githubusercontent.com/17545154/153112913-0ce7ca21-fe40-4b3d-afca-405ad0e31f6c.png)

像这个方法 
  @protected
  @mustCallSuper
  void dispose() {}

文档是这样说的 
“Implementations of this method should end with a call to the inherited method, as in `super.dispose()`.”
应该是最后调用

**Comment by wendux** [comment]
fixed
