### ISSUE TITLE
2.4.5 命名路由#适配 代码第五行问题

### ISSUE THREAD

**Issue by FerostMask** [flutterchina/flutter_in_action_2nd#87]
Flutter版本2.10.1，提示

- The property 'settings' can't be unconditionally accessed because the receiver can be 'null'.

- The argument type 'Object?' can't be assigned to the parameter type 'String'.

更改为：
return TipRoute(text: ModalRoute.of(context)!.settings.arguments.toString());问题修复

**Comment by wendux** [comment]
fix
