### ISSUE TITLE
勘误：2.1.2首页部分内容与2.2.6章节中文字重复

### ISSUE THREAD

**Issue by kelly6** [flutterchina/flutter_in_action_2nd#88]
2.1.2首页章节中   “为什么要将 build 方法放在 State 中，而不是放在StatefulWidget中？”
在2.2.6中完整重复了一遍
![image](https://user-images.githubusercontent.com/6754377/155304304-101e0dec-f88e-4637-9e96-1697effb7efb.png)

![image](https://user-images.githubusercontent.com/6754377/155304457-c95fb77e-0902-438b-a932-ce73683e7c46.png)

并且2.2.6中少了个“放”字

**Comment by wendux** [comment]
已删
