### ISSUE TITLE
1.1.1 跨平台技术简介语句存在问题

### ISSUE THREAD

**Issue by wangjing013** [flutterchina/flutter_in_action_2nd#96]
[针对原生开发面临(的)问题，业界一直都在努力寻找好的解决方案](https://book.flutterchina.club/chapter1/mobile_development_intro.html#_1-1-1-%E5%8E%9F%E7%94%9F%E5%BC%80%E5%8F%91%E4%B8%8E%E8%B7%A8%E5%B9%B3%E5%8F%B0%E6%8A%80%E6%9C%AF)

**Comment by wendux** [comment]
已修改
